services:
  app:
    container_name: app
    image: app:dev
    build:
      context: .
      args:
        VERSION: dev
    environment:
      PORT: 8080
    ports:
      - "88:8080"
    volumes:
      - ./public:/var/www/app/public
      - ./vendor:/var/www/app/vendor
